generate-icons:
	inkscape -w 72 -h 72 src/assets/icons/icon.svg --export-png=src/assets/icons/icon-72x72.png
	inkscape -w 96 -h 96 src/assets/icons/icon.svg --export-png=src/assets/icons/icon-96x96.png
	inkscape -w 128 -h 128 src/assets/icons/icon.svg --export-png=src/assets/icons/icon-128x128.png
	inkscape -w 144 -h 144 src/assets/icons/icon.svg --export-png=src/assets/icons/icon-144x144.png
	inkscape -w 152 -h 152 src/assets/icons/icon.svg --export-png=src/assets/icons/icon-152x152.png
	inkscape -w 192 -h 192 src/assets/icons/icon.svg --export-png=src/assets/icons/icon-192x192.png
	inkscape -w 384 -h 384 src/assets/icons/icon.svg --export-png=src/assets/icons/icon-384x384.png
	inkscape -w 512 -h 512 src/assets/icons/icon.svg --export-png=src/assets/icons/icon-512x512.png

generate-favicons:
	inkscape -w 180 -h 180 src/assets/icons/icon.svg --export-png=src/assets/favicon/apple-touch-icon.png
	inkscape -w 32 -h 32 src/assets/icons/icon.svg --export-png=src/assets/favicon/favicon-32x32.png
	inkscape -w 16 -h 16 src/assets/icons/icon.svg --export-png=src/assets/favicon/favicon-16x16.png
