security:
    enable_authenticator_manager: true
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        users_in_memory: { memory: null }
#        auth_user_provider:
#            entity:
#                class: Sywer\AuthBundle\Entity\User
#                property: email#
        cabinet_user_provider:
            id: App\Security\Cabinet\UserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_refresh:
            anonymous: false
            stateless: true
            pattern: ^/api/v1/refresh
            custom_authenticators:
                - App\Security\Api\RefreshTokenAuthenticator

        api_login:
            anonymous: false
            stateless: true
            pattern: ^/api/v1/login
#            json_login:
#                check_path: auth_login
#                username_path: email
#                password_path: password
            custom_authenticators:
                - App\Security\Api\LoginAuthenticator

        api:
            anonymous: false
            pattern: ^/api/v1
            stateless: true
            custom_authenticators:
                - App\Security\Api\AccessTokenAuthenticator

        cabinet:
            pattern: ^/
            lazy: true
#            provider: users_in_memory
#            switch_user: true
            custom_authenticators:
                - App\Security\Cabinet\LoginFormAuthenticator
            logout:
                path: app_logout

    access_control:
        - { path: ^/cabinet/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/cabinet/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/cabinet/reset_password, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/v1/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: ROLE_USER }
        - { path: ^/, roles: ROLE_USER }
