security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        users_in_memory: { memory: null }
        cabinet_user_provider:
            id: App\Security\Cabinet\UserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_refresh:
            anonymous: false
            stateless: true
            pattern: ^/api/v1/refresh
            custom_authenticators:
                - App\Security\Api\RefreshTokenAuthenticator

        api_login:
            anonymous: false
            stateless: true
            pattern: ^/api/v1/login
            custom_authenticators:
                - App\Security\Api\LoginAuthenticator

        api:
            anonymous: false
            pattern: ^/api/v1
            stateless: true
            custom_authenticators:
                - App\Security\Api\AccessTokenAuthenticator

        cabinet:
            pattern: ^/
            lazy: true
            custom_authenticators:
                - App\Security\Cabinet\LoginFormAuthenticator
            logout:
                path: app_logout

    access_control:
        - { path: ^/cabinet/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/cabinet/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/cabinet/reset_password, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/v1/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: ROLE_USER }
        - { path: ^/, roles: ROLE_USER }
