parameters:
  frontend_url: '%env(FRONTEND_BASE_URL)%'
  avatar_public_dir: '/uploads/avatars'
  avatar_upload_dir: '%kernel.project_dir%/public%avatar_public_dir%'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'
      - '../src/Tests/'

  App\Model\Mailer:
    $fromEmail: '%env(MAILER_FROM_EMAIL)%'
    $fromName: '%env(MAILER_FROM_NAME)%'

  App\Model\User\Service\AccessTokenManager:
    $privateKeyPath: '%env(JWT_PRIVATE_KEY_PATH)%'
    $publicKeyPath: '%env(JWT_PUBLIC_KEY_PATH)%'
    $passphrase: '%env(JWT_PASSPHRASE)%'

  App\Model\User\Service\RefreshTokenManager:
    $privateKeyPath: '%env(JWT_PRIVATE_KEY_PATH)%'
    $publicKeyPath: '%env(JWT_PUBLIC_KEY_PATH)%'
    $passphrase: '%env(JWT_PASSPHRASE)%'
    $encryptionKey: '%env(JWT_ENCRYPTION_KEY)%'

  App\Model\Progress\EventListener\:
    resource: '../src/Model/Progress/EventListener/*'
    tags:
      - { name: kernel.event_listener }

  App\Model\User\Service\ConfirmRequestSender:
    $frontendUrl: '%frontend_url%'

  App\Model\Progress\Service\InviteSender:
    $frontendUrl: '%frontend_url%'

  Liip\ImagineBundle\Service\FilterService:
    alias: 'liip_imagine.service.filter'

  App\Model\User\UseCase\ChangeAvatar\Handler:
    $publicDir: '%avatar_public_dir%'
    $uploadDir: '%avatar_upload_dir%'